public enum State {
    INIT,
    DURING_LOGIN,
    DURING_REGISTRATION,
    LOGGED_IN,
    STOP,
    LOGOUT,
    SHOWING_CATEGORY,
    ADDING_AUCTION,
    LISTING_AUCTIONS,
    WINNING_AUCTIONS,
    MAKING_OFFER,
}
